export const LIST_PRODUCT = "LIST_PRODUCT";
export const BUY_ITEM = "BUY_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CHANGE_NOTIFY = "CHANGE_NOTIFY";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
