const categories = [
  {
    id: 7,
    title: "PHÒNG KHÁCH",
    icon: "../img/loai-sp/icon-phong-khach.png",
    mateTitle: "Nội thất phòng khách",
    metaKeyword: "nội thất phòng khách giá tốt",
    metaDescription:
      "Tìm kiếm nội thất phòng khách chất lượng với giá cả phải chăng",
    slug: "phong-khach",
    orders: 1,
    parentid: null,
    createdDate: "2024-09-29",
    updatedDate: "2024-09-29",
    adminCreated: "admin1",
    adminUpdated: "admin2",
    notes: "Danh mục nội thất phòng khách đa dạng",
    status: 1,
    isdelete: 0,
  },
  {
    id: 8,
    title: "PHÒNG NGỦ",
    icon: "../img/loai-sp/icon-phong-ngu.png",
    mateTitle: "Nội thất phòng ngủ",
    metaKeyword: "nội thất phòng ngủ giá tốt",
    metaDescription: "Khám phá nội thất phòng ngủ hiện đại, tiện nghi",
    slug: "phong-ngu",
    orders: 2,
    parentid: null,
    createdDate: "2024-09-29",
    updatedDate: "2024-09-29",
    adminCreated: "admin1",
    adminUpdated: "admin3",
    notes: "Phòng ngủ với nhiều kiểu dáng và thiết kế",
    status: 1,
    isdelete: 0,
  },
  {
    id: 10,
    title: "PHÒNG BẾP",
    icon: "../img/loai-sp/icon-phong-bep.png",
    mateTitle: "Nội thất phòng ăn",
    metaKeyword: "nội thất phòng ăn giá tốt",
    metaDescription: "Bộ sưu tập nội thất phòng ăn sang trọng, tiện lợi",
    slug: "phong-an",
    orders: 3,
    parentid: null,
    createdDate: "2024-09-29",
    updatedDate: "2024-09-29",
    adminCreated: "admin2",
    adminUpdated: "admin4",
    notes: "Thiết kế hiện đại, tối ưu không gian",
    status: 1,
    isdelete: 0,
  },
  {
    id: 12,
    title: "PHÒNG TRẺ EM",
    icon: "../img/loai-sp/icon-tre-em.png",
    mateTitle: "Nội thất phòng trẻ em",
    metaKeyword: "nội thất phòng trẻ em giá tốt",
    metaDescription: "Thiết kế nội thất phòng trẻ em an toàn, đáng yêu",
    slug: "phong-tre-em",
    orders: 4,
    parentid: null,
    createdDate: "2024-09-29",
    updatedDate: "2024-09-29",
    adminCreated: "admin1",
    adminUpdated: "admin5",
    notes: "Không gian sáng tạo và thoải mái cho trẻ em",
    status: 1,
    isdelete: 0,
  },
  {
    id: 13,
    title: "VĂN PHÒNG",
    icon: "../img/loai-sp/icon-van-phong.png",
    mateTitle: "Nội thất văn phòng",
    metaKeyword: "nội thất văn phòng giá tốt",
    metaDescription: "Nội thất văn phòng hiện đại, phong cách chuyên nghiệp",
    slug: "van-phong",
    orders: 5,
    parentid: null,
    createdDate: "2024-09-29",
    updatedDate: "2024-09-29",
    adminCreated: "admin3",
    adminUpdated: "admin4",
    notes: "Tối ưu không gian làm việc với thiết kế hiện đại",
    status: 1,
    isdelete: 0,
  },
  {
    id: 11,
    title: "PHÒNG TẮM",
    icon: "../img/loai-sp/icon-phong-tam.png",
    mateTitle: "Nội thất phòng tắm",
    metaKeyword: "nội thất phòng tắm giá tốt",
    metaDescription: "Bộ sưu tập nội thất phòng tắm cao cấp, tiện nghi",
    slug: "phong-tam",
    orders: 6,
    parentid: null,
    createdDate: "2024-09-29",
    updatedDate: "2024-09-29",
    adminCreated: "admin2",
    adminUpdated: "admin5",
    notes: "Nội thất sang trọng, tiết kiệm diện tích",
    status: 1,
    isdelete: 0,
  },
  {
    id: 15,
    title: "Đồ trang trí",
    icon: "../img/loai-sp/icon-do-trang-tri.png",
    mateTitle: "Nội thất Đồ trang trí",
    metaKeyword: "nội thất Đồ trang trí giá tốt",
    metaDescription: "Trang trí nội thất Đồ trang trí đẹp mắt, ấn tượng",
    slug: "ban-cong",
    orders: 7,
    parentid: null,
    createdDate: "2024-09-29",
    updatedDate: "2024-09-29",
    adminCreated: "admin1",
    adminUpdated: "admin3",
    notes: "Thiết kế không gian mở với phong cách độc đáo",
    status: 1,
    isdelete: 0,
  },
  {
    id: 14,
    title: "Cầu thang",
    icon: "../img/loai-sp/icon-cau-thang.png",
    mateTitle: "Nội thất Cầu thang",
    metaKeyword: "nội thất Cầu thang giá tốt",
    metaDescription: "Nội thất Cầu thang đẹp, bền vững với môi trường",
    slug: "san-vuon",
    orders: 8,
    parentid: null,
    createdDate: "2024-09-29",
    updatedDate: "2024-09-29",
    adminCreated: "admin4",
    adminUpdated: "admin5",
    notes: "Thiết kế xanh thân thiện với môi trường",
    status: 1,
    isdelete: 0,
  },
];

export default categories;
