const news = [
  {
    id: 10,
    code: null,
    title: "NGẤT NGÂY VỚI TOP 10 MẪU NỘI THẤT CHUNG CƯ 1 PHÒNG NGỦ ĐẸP",
    description:
      "Những căn hộ chung cư mini,  diện  nhỏ   trở  ưa chuộng hơn trong cuộc sống hiện đại với những ai  khoản kinh hạn hẹp",
    content:
      "Những căn hộ chung cư mini,  diện  nhỏ   trở  ưa chuộng hơn trong cuộc sống hiện đại với những ai  khoản kinh hạn hẹp",
    image: "../img/tintuc-4.png",
    metaTitle: "NGẤT NGÂY VỚI TOP 10 MẪU NỘI THẤT CHUNG CƯ 1 PHÒNG NGỦ ĐẸP",
    mainKeyword: "NGẤT NGÂY VỚI TOP 10 MẪU NỘI THẤT CHUNG CƯ 1 PHÒNG NGỦ ĐẸP",
    metaKeyword: "NGẤT NGÂY VỚI TOP 10 MẪU NỘI THẤT CHUNG CƯ 1 PHÒNG NGỦ ĐẸP",
    metaDescription:
      'Những căn hộ chung cư mini, có diện tích nhỏ ngày càng trở nên nên ưa chuộng hơn trong cuộc sống hiện đại với những ai có khoản kinh phí "hạn hẹp".\n',
    slug: "ngat-ngay-voi-top-10-mau-noi-that-chung-cu-1-phong-ngu-dep",
    views: 0,
    likes: 0,
    star: null,
    createdDate: "2020-07-30T23:46:34.473",
    updatedDate: "2020-07-30T23:46:34.473",
    adminCreated: null,
    adminUpdated: null,
    status: 1,
    isdelete: null,
  },
  {
    id: 11,
    code: null,
    title: "25+ MẪU GIƯỜNG NGỦ HỘC KÉO THÔNG MINH CHO CĂN PHÒNG BẠN",
    description:
      "Sự thật  ta  hết 1/3 cuộc đời chỉ để ngủ,  thế việc tạo được một giấc ngủ ngon  một điều đặc biệt quan trọng.",
    content:
      '\u003Cimg alt="NGẤT NGÂY VỚI TOP 10 MẪU NỘI THẤT CHUNG CƯ 1 PHÒNG NGỦ ĐẸP" src="/Content/Uploads/images/tin-tuc/tintuc-2.png" /\u003E\nSự thật  ta  hết 1/3 cuộc đời chỉ để ngủ,  thế việc tạo được một giấc ngủ ngon  một điều đặc biệt quan trọng.',
    image: "../img/tintuc-3.jpg",
    metaTitle: "25+ MẪU GIƯỜNG NGỦ HỘC KÉO THÔNG MINH CHO CĂN PHÒNG BẠN",
    mainKeyword: "25+ MẪU GIƯỜNG NGỦ HỘC KÉO THÔNG MINH CHO CĂN PHÒNG BẠN",
    metaKeyword: "25+ MẪU GIƯỜNG NGỦ HỘC KÉO THÔNG MINH CHO CĂN PHÒNG BẠN",
    metaDescription:
      "Sự thật là chúng ta dành hết 1/3 cuộc đời chỉ để ngủ, vì thế việc tạo được một giấc ngủ ngon là một điều đặc biệt quan trọng.\n",
    slug: "25--mau-giuong-ngu-hoc-keo-thong-minh-cho-can-phong-ban",
    views: 0,
    likes: 0,
    star: null,
    createdDate: "2020-07-30T00:00:00",
    updatedDate: "2020-07-30T00:00:00",
    adminCreated: null,
    adminUpdated: null,
    status: 1,
    isdelete: null,
  },
  {
    id: 12,
    code: null,
    title: "TUYỆT CHIÊU THIẾT KẾ CHUNG CƯ MINI 2 PHÒNG NGỦ SIÊU ĐẸP",
    description:
      "Độ tuổi khởi nghiệp  tự lập   trẻ  trong  hội hiện đại thời nay, thế việc &ldquo;thiết kế căn hộ chung cư mini 2  ngủ",
    content:
      '\u003Cimg alt="Độ tuổi khởi nghiệp và tự lập ngày càng trẻ hóa trong xã hội hiện đại thời nay, thế nên việc “thiết kế căn hộ chung cư mini 2 phòng ngủ”" src="/Content/Uploads/images/tin-tuc/tintuc-3.png" /\u003E\nĐộ tuổi khởi nghiệp  tự lập   trẻ  trong  hội hiện đại thời nay, thế việc &ldquo;thiết kế căn hộ chung cư mini 2 ph&ograve;ng ngủ',
    image: "../img/tintuc-4.jpg",
    metaTitle: "TUYỆT CHIÊU THIẾT KẾ CHUNG CƯ MINI 2 PHÒNG NGỦ SIÊU ĐẸP",
    mainKeyword: "TUYỆT CHIÊU THIẾT KẾ CHUNG CƯ MINI 2 PHÒNG NGỦ SIÊU ĐẸP",
    metaKeyword: "TUYỆT CHIÊU THIẾT KẾ CHUNG CƯ MINI 2 PHÒNG NGỦ SIÊU ĐẸP",
    metaDescription:
      "Độ tuổi khởi nghiệp và tự lập ngày càng trẻ hóa trong xã hội hiện đại thời nay, thế nên việc “thiết kế căn hộ chung cư mini 2 phòng ngủ”\n",
    slug: "tuyet-chieu-thiet-ke-chung-cu-mini-2-phong-ngu-sieu-dep",
    views: 0,
    likes: 0,
    star: null,
    createdDate: "2020-07-30T23:49:44.293",
    updatedDate: "2020-07-30T23:49:44.293",
    adminCreated: null,
    adminUpdated: null,
    status: 1,
    isdelete: null,
  },
  {
    id: 13,
    code: null,
    title: "NGẤT NGÂY VỚI TOP 10 MẪU NỘI THẤT CHUNG CƯ 1 PHÒNG NGỦ ĐẸP",
    description:
      "Những căn hộ chung cư mini,  diện  nhỏ   trở  ưa chuộng hơn trong cuộc sống hiện đại với những ai  khoản kinh hạn hẹp",
    content:
      '\u003Cimg alt="Những căn hộ chung cư mini, có diện tích nhỏ ngày càng trở nên nên ưa chuộng hơn trong cuộc sống hiện đại với những ai có khoản kinh phí &quot;hạn hẹp&quot;." src="/Content/Uploads/images/tin-tuc/tintuc-4.png" /\u003E\nNhững căn hộ chung cư mini,  diện  nhỏ   trở  ưa chuộng hơn trong cuộc sống hiện đại với những ai  khoản kinh hạn hẹp',
    image: "../img/tintuc-4.png",
    metaTitle: "NGẤT NGÂY VỚI TOP 10 MẪU NỘI THẤT CHUNG CƯ 1 PHÒNG NGỦ ĐẸP",
    mainKeyword: "NỘI THẤT CHUNG ",
    metaKeyword: "NGẤT NGÂY VỚI TOP 10 MẪU NỘI THẤT CHUNG CƯ 1 PHÒNG NGỦ ĐẸP",
    metaDescription:
      'Những căn hộ chung cư mini, có diện tích nhỏ ngày càng trở nên nên ưa chuộng hơn trong cuộc sống hiện đại với những ai có khoản kinh phí "hạn hẹp".\n',
    slug: "ngat-ngay-voi-top-10-mau-noi-that-chung-cu-1-phong-ngu-dep",
    views: 0,
    likes: 0,
    star: null,
    createdDate: "2020-07-30T23:51:22.097",
    updatedDate: "2020-07-30T23:51:22.097",
    adminCreated: null,
    adminUpdated: null,
    status: 1,
    isdelete: null,
  },
  {
    id: 14,
    code: null,
    title: "25+ MẪU GIƯỜNG NGỦ HỘC KÉO THÔNG MINH CHO CĂN PHÒNG BẠN",
    description:
      "Sự thật  ta  hết 1/3 cuộc đời chỉ để ngủ,  thế việc tạo được một giấc ngủ ngon  một điều đặc biệt quan trọng.",
    content:
      '\u003Cimg alt="Sự thật là chúng ta dành hết 1/3 cuộc đời chỉ để ngủ, vì thế việc tạo được một giấc ngủ ngon là một điều đặc biệt quan trọng." src="/Content/Uploads/images/tin-tuc/tintuc-5.png" /\u003E\nSự thật  ta  hết 1/3 cuộc đời chỉ để ngủ,  thế việc tạo được một giấc ngủ ngon  một điều đặc biệt quan trọng.',
    image: "../img/tintuc-5.png",
    metaTitle: "25+ MẪU GIƯỜNG NGỦ HỘC KÉO THÔNG MINH CHO CĂN PHÒNG BẠN",
    mainKeyword: "GIƯỜNG NGỦ HỘC KÉO THÔNG MINH",
    metaKeyword: "25+ MẪU GIƯỜNG NGỦ HỘC KÉO THÔNG MINH CHO CĂN PHÒNG BẠN",
    metaDescription:
      "Sự thật là chúng ta dành hết 1/3 cuộc đời chỉ để ngủ, vì thế việc tạo được một giấc ngủ ngon là một điều đặc biệt quan trọng.\n",
    slug: "25--mau-giuong-ngu-hoc-keo-thong-minh-cho-can-phong-ban",
    views: 0,
    likes: 0,
    star: null,
    createdDate: "2020-07-30T23:53:12.677",
    updatedDate: "2020-07-30T23:53:12.677",
    adminCreated: null,
    adminUpdated: null,
    status: 1,
    isdelete: null,
  },
  {
    id: 15,
    code: null,
    title: "TUYỆT CHIÊU THIẾT KẾ CHUNG CƯ MINI 2 PHÒNG NGỦ SIÊU ĐẸP",
    description:
      "Độ tuổi khởi nghiệp  tự lập   trẻ  trong  hội hiện đại thời nay, thế việc &ldquo;thiết kế căn hộ chung cư mini 2  ngủ",
    content:
      '\u003Cimg alt="Độ tuổi khởi nghiệp và tự lập ngày càng trẻ hóa trong xã hội hiện đại thời nay, thế nên việc “thiết kế căn hộ chung cư mini 2 phòng ngủ”" src="/Content/Uploads/images/tin-tuc/tintuc-6.png" /\u003E\nĐộ tuổi khởi nghiệp  tự lập   trẻ  trong  hội hiện đại thời nay, thế việc &ldquo;thiết kế căn hộ chung cư mini 2  ngủ',
    image: "../img/tintuc-6.png",
    metaTitle: "TUYỆT CHIÊU THIẾT KẾ CHUNG CƯ MINI 2 PHÒNG NGỦ SIÊU ĐẸP",
    mainKeyword: "THIẾT KẾ CHUNG CƯ MINI ",
    metaKeyword: "TUYỆT CHIÊU THIẾT KẾ CHUNG CƯ MINI 2 PHÒNG NGỦ SIÊU ĐẸP",
    metaDescription:
      "Độ tuổi khởi nghiệp và tự lập ngày càng trẻ hóa trong xã hội hiện đại thời nay, thế nên việc “thiết kế căn hộ chung cư mini 2 phòng ngủ”\n",
    slug: "tuyet-chieu-thiet-ke-chung-cu-mini-2-phong-ngu-sieu-dep",
    views: 0,
    likes: 0,
    star: null,
    createdDate: "2020-07-30T23:54:35.957",
    updatedDate: "2020-07-30T23:54:35.957",
    adminCreated: null,
    adminUpdated: null,
    status: 1,
    isdelete: null,
  },
];

export default news;
